kind: Pod
apiVersion: v1
metadata:
  name: kppod
  labels:                                                   
    env: development
    class: pods
    owner: basitihsan
spec:
  containers:
   - name: c00
     image: ubuntu
     command: ["/bin/bash", "-c", "while true; do echo Hello-Basit; sleep 5 ; done"]

    

